// ------------------------------------------------------------------------------
// <auto-generated> 
//     Este código fue generado por una herramienta. WooW.SB ttModelo
//     Versión del runtime: 1.0.0.0
//  
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
// ------------------------------------------------------------------------------//
using System; 
using System.Runtime.Serialization;
using ServiceStack;
using ServiceStack.DataAnnotations;
using WooW.Core;
using Newtonsoft.Json;
using WooW.Resources.Labels;


#nullable disable

namespace WooW.Model
{




    #if SERVER
    [AutoApply(Behavior.AuditQuery)]
    #endif
    [Tag("WoIntrinsic")]
    [Route("/api/WoMenusReq", "GET")]
    //[WoLabel(Descripcion = nameof(WooW_Label.ObtieneMenus))]
    [WoModelMeta(
        ProcesoId = "SYS",
        TipoModelo = WoTypeModel.Request,
        Filtro = woGetListFilterType.Ninguno,
        Legacy  = "")]
    [JsonObject(MemberSerialization.OptOut)]
    public  partial class WoMenusReq : IWoInstanciaUdn
    {
        public WoMenusReq()
        {
        }

    }
}
