 
  
// ------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta. WooW.SB ttModeloRequestServicioCliente.tt
//     Versión del runtime: 1.0.0.0
//  
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
// ------------------------------------------------------------------------------//
using WooW.Core; 
using WooW.DTO;
using ServiceStack;

namespace WooW.Model
{
    public partial class WoReportListReq
    {
        public static WoReportListRes Get(
            JsonApiClient Client, WoReportListReq Request)
        {
            return Client.Get<WoReportListRes>(Request);
        }

        public static async Task<WoReportListRes> GetAsync(
            JsonApiClient Client, WoReportListReq Request)
        {
            return await Client.GetAsync<WoReportListRes>(Request);
        }




    }
}
