//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WooW.Resources.Labels {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WooW_Label {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WooW_Label() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WooW.Resources.Labels.WooW_Label", typeof(WooW_Label).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrador De Datos Maestros.
        /// </summary>
        public static string AdministradorDeDatosMaestros {
            get {
                return ResourceManager.GetString("AdministradorDeDatosMaestros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrador Del Sistema.
        /// </summary>
        public static string AdministradorDelSistema {
            get {
                return ResourceManager.GetString("AdministradorDelSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Año.
        /// </summary>
        public static string Anio {
            get {
                return ResourceManager.GetString("Anio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anterior.
        /// </summary>
        public static string Anterior {
            get {
                return ResourceManager.GetString("Anterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Auxiliar De Compras.
        /// </summary>
        public static string AuxiliarDeCompras {
            get {
                return ResourceManager.GetString("AuxiliarDeCompras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Auxiliar De Contabilidad.
        /// </summary>
        public static string AuxiliarDeContabilidad {
            get {
                return ResourceManager.GetString("AuxiliarDeContabilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Auxiliar De Cuentas Por Cobrar.
        /// </summary>
        public static string AuxiliarDeCuentasPorCobrar {
            get {
                return ResourceManager.GetString("AuxiliarDeCuentasPorCobrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Auxiliar De Cuentas Por Pagar.
        /// </summary>
        public static string AuxiliarDeCuentasPorPagar {
            get {
                return ResourceManager.GetString("AuxiliarDeCuentasPorPagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Auxiliar De Datos Maestros.
        /// </summary>
        public static string AuxiliarDeDatosMaestros {
            get {
                return ResourceManager.GetString("AuxiliarDeDatosMaestros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Auxiliar De Facturacion.
        /// </summary>
        public static string AuxiliarDeFacturacion {
            get {
                return ResourceManager.GetString("AuxiliarDeFacturacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Auxiliar De Inventario.
        /// </summary>
        public static string AuxiliarDeInventario {
            get {
                return ResourceManager.GetString("AuxiliarDeInventario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Auxiliar De Nomina.
        /// </summary>
        public static string AuxiliarDeNomina {
            get {
                return ResourceManager.GetString("AuxiliarDeNomina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Auxiliar De Tesoreria.
        /// </summary>
        public static string AuxiliarDeTesoreria {
            get {
                return ResourceManager.GetString("AuxiliarDeTesoreria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bancos.
        /// </summary>
        public static string Bancos {
            get {
                return ResourceManager.GetString("Bancos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calcular.
        /// </summary>
        public static string Calcular {
            get {
                return ResourceManager.GetString("Calcular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar transición.
        /// </summary>
        public static string CancelarTransicion {
            get {
                return ResourceManager.GetString("CancelarTransicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Casado.
        /// </summary>
        public static string Casado {
            get {
                return ResourceManager.GetString("Casado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente Web.
        /// </summary>
        public static string ClienteWeb {
            get {
                return ResourceManager.GetString("ClienteWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compartir.
        /// </summary>
        public static string Compartir {
            get {
                return ResourceManager.GetString("Compartir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compras.
        /// </summary>
        public static string Compras {
            get {
                return ResourceManager.GetString("Compras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contabilidad.
        /// </summary>
        public static string Contabilidad {
            get {
                return ResourceManager.GetString("Contabilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contar Divorciados.
        /// </summary>
        public static string ContarDivorciados {
            get {
                return ResourceManager.GetString("ContarDivorciados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copiar al portapapeles.
        /// </summary>
        public static string CopiarAlPortapapeles {
            get {
                return ResourceManager.GetString("CopiarAlPortapapeles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuentas Por Cobrar.
        /// </summary>
        public static string CuentasPorCobrar {
            get {
                return ResourceManager.GetString("CuentasPorCobrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuentas Por Pagar.
        /// </summary>
        public static string CuentasPorPagar {
            get {
                return ResourceManager.GetString("CuentasPorPagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos.
        /// </summary>
        public static string Datos {
            get {
                return ResourceManager.GetString("Datos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Maestros.
        /// </summary>
        public static string DatosMaestros {
            get {
                return ResourceManager.GetString("DatosMaestros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Divorciado.
        /// </summary>
        public static string Divorciado {
            get {
                return ResourceManager.GetString("Divorciado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar registro.
        /// </summary>
        public static string EliminarRegistro {
            get {
                return ResourceManager.GetString("EliminarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empleados.
        /// </summary>
        public static string Empleados {
            get {
                return ResourceManager.GetString("Empleados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entradas.
        /// </summary>
        public static string Entradas {
            get {
                return ResourceManager.GetString("Entradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        public static string Enviar {
            get {
                return ResourceManager.GetString("Enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar Transición.
        /// </summary>
        public static string EnviarTransicion {
            get {
                return ResourceManager.GetString("EnviarTransicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español Mexicano.
        /// </summary>
        public static string EspañolMexicano {
            get {
                return ResourceManager.GetString("EspañolMexicano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este campo es requerido y no puede quedar vacio.
        /// </summary>
        public static string EsteCampoEsRequeridoYNoPuedeQuedarVacio {
            get {
                return ResourceManager.GetString("EsteCampoEsRequeridoYNoPuedeQuedarVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Explorar.
        /// </summary>
        public static string Explorar {
            get {
                return ResourceManager.GetString("Explorar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facturacion.
        /// </summary>
        public static string Facturacion {
            get {
                return ResourceManager.GetString("Facturacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formulario.
        /// </summary>
        public static string Formulario {
            get {
                return ResourceManager.GetString("Formulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formulario de control.
        /// </summary>
        public static string FormularioDeControl {
            get {
                return ResourceManager.GetString("FormularioDeControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string Idioma {
            get {
                return ResourceManager.GetString("Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingles Norteamericano.
        /// </summary>
        public static string InglesNorteamericano {
            get {
                return ResourceManager.GetString("InglesNorteamericano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        public static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inventarios.
        /// </summary>
        public static string Inventarios {
            get {
                return ResourceManager.GetString("Inventarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir a formulario.
        /// </summary>
        public static string IrAFormulario {
            get {
                return ResourceManager.GetString("IrAFormulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lectura.
        /// </summary>
        public static string Lectura {
            get {
                return ResourceManager.GetString("Lectura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar.
        /// </summary>
        public static string Limpiar {
            get {
                return ResourceManager.GetString("Limpiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista.
        /// </summary>
        public static string Lista {
            get {
                return ResourceManager.GetString("Lista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Página.
        /// </summary>
        public static string NuevaPagina {
            get {
                return ResourceManager.GetString("NuevaPagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Submenú.
        /// </summary>
        public static string NuevoSubmenu {
            get {
                return ResourceManager.GetString("NuevoSubmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parámetros.
        /// </summary>
        public static string Parametros {
            get {
                return ResourceManager.GetString("Parametros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primero.
        /// </summary>
        public static string Primero {
            get {
                return ResourceManager.GetString("Primero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puede Activar.
        /// </summary>
        public static string PuedeActivar {
            get {
                return ResourceManager.GetString("PuedeActivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puede Afectar Registro.
        /// </summary>
        public static string PuedeAfectarRegistro {
            get {
                return ResourceManager.GetString("PuedeAfectarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puede Borrar.
        /// </summary>
        public static string PuedeBorrar {
            get {
                return ResourceManager.GetString("PuedeBorrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puede Contabilizar.
        /// </summary>
        public static string PuedeContabilizar {
            get {
                return ResourceManager.GetString("PuedeContabilizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puede Dar De Alta.
        /// </summary>
        public static string PuedeDarDeAlta {
            get {
                return ResourceManager.GetString("PuedeDarDeAlta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puede Dar De Baja.
        /// </summary>
        public static string PuedeDarDeBaja {
            get {
                return ResourceManager.GetString("PuedeDarDeBaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puede Descartar.
        /// </summary>
        public static string PuedeDescartar {
            get {
                return ResourceManager.GetString("PuedeDescartar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puede Descontabilizar.
        /// </summary>
        public static string PuedeDescontabilizar {
            get {
                return ResourceManager.GetString("PuedeDescontabilizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puede Generar Reportes.
        /// </summary>
        public static string PuedeGenerarReportes {
            get {
                return ResourceManager.GetString("PuedeGenerarReportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puede Importar Datos.
        /// </summary>
        public static string PuedeImportarDatos {
            get {
                return ResourceManager.GetString("PuedeImportarDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puede Modificar.
        /// </summary>
        public static string PuedeModificar {
            get {
                return ResourceManager.GetString("PuedeModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puede Modificar Datos Contables.
        /// </summary>
        public static string PuedeModificarDatosContables {
            get {
                return ResourceManager.GetString("PuedeModificarDatosContables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puede Modificar Parametros.
        /// </summary>
        public static string PuedeModificarParametros {
            get {
                return ResourceManager.GetString("PuedeModificarParametros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puede Modificar Registro.
        /// </summary>
        public static string PuedeModificarRegistro {
            get {
                return ResourceManager.GetString("PuedeModificarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puede Registrar.
        /// </summary>
        public static string PuedeRegistrar {
            get {
                return ResourceManager.GetString("PuedeRegistrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puede Registrar Y Afectar.
        /// </summary>
        public static string PuedeRegistrarYAfectar {
            get {
                return ResourceManager.GetString("PuedeRegistrarYAfectar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puede Suspender.
        /// </summary>
        public static string PuedeSuspender {
            get {
                return ResourceManager.GetString("PuedeSuspender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recalcular.
        /// </summary>
        public static string Recalcular {
            get {
                return ResourceManager.GetString("Recalcular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Refrescar.
        /// </summary>
        public static string Refrescar {
            get {
                return ResourceManager.GetString("Refrescar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rol.
        /// </summary>
        public static string Rol {
            get {
                return ResourceManager.GetString("Rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguro que desea eliminar el registro.
        /// </summary>
        public static string SeguroQueDeseaEliminarElRegistro {
            get {
                return ResourceManager.GetString("SeguroQueDeseaEliminarElRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar.
        /// </summary>
        public static string Seleccionar {
            get {
                return ResourceManager.GetString("Seleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione vista.
        /// </summary>
        public static string SeleccioneVista {
            get {
                return ResourceManager.GetString("SeleccioneVista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicio Web.
        /// </summary>
        public static string ServicioWeb {
            get {
                return ResourceManager.GetString("ServicioWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si.
        /// </summary>
        public static string Si {
            get {
                return ResourceManager.GetString("Si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        public static string Siguiente {
            get {
                return ResourceManager.GetString("Siguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistema.
        /// </summary>
        public static string Sistema {
            get {
                return ResourceManager.GetString("Sistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistema De Administracion Tributaria.
        /// </summary>
        public static string SistemaDeAdministracionTributaria {
            get {
                return ResourceManager.GetString("SistemaDeAdministracionTributaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soltero.
        /// </summary>
        public static string Soltero {
            get {
                return ResourceManager.GetString("Soltero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Supervisor De Compras.
        /// </summary>
        public static string SupervisorDeCompras {
            get {
                return ResourceManager.GetString("SupervisorDeCompras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Supervisor De Contabilidad.
        /// </summary>
        public static string SupervisorDeContabilidad {
            get {
                return ResourceManager.GetString("SupervisorDeContabilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Supervisor De Cuentas Por Cobrar.
        /// </summary>
        public static string SupervisorDeCuentasPorCobrar {
            get {
                return ResourceManager.GetString("SupervisorDeCuentasPorCobrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Supervisor De Cuentas Por Pagar.
        /// </summary>
        public static string SupervisorDeCuentasPorPagar {
            get {
                return ResourceManager.GetString("SupervisorDeCuentasPorPagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Supervisor De Facturacion.
        /// </summary>
        public static string SupervisorDeFacturacion {
            get {
                return ResourceManager.GetString("SupervisorDeFacturacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Supervisor De Inventario.
        /// </summary>
        public static string SupervisorDeInventario {
            get {
                return ResourceManager.GetString("SupervisorDeInventario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Supervisor De Nomina.
        /// </summary>
        public static string SupervisorDeNomina {
            get {
                return ResourceManager.GetString("SupervisorDeNomina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Supervisor De Tesoreria.
        /// </summary>
        public static string SupervisorDeTesoreria {
            get {
                return ResourceManager.GetString("SupervisorDeTesoreria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tema.
        /// </summary>
        public static string Tema {
            get {
                return ResourceManager.GetString("Tema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tesoreria.
        /// </summary>
        public static string Tesoreria {
            get {
                return ResourceManager.GetString("Tesoreria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de Empleados.
        /// </summary>
        public static string TiposDeEmpleados {
            get {
                return ResourceManager.GetString("TiposDeEmpleados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transición.
        /// </summary>
        public static string Transicion {
            get {
                return ResourceManager.GetString("Transicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Último.
        /// </summary>
        public static string Ultimo {
            get {
                return ResourceManager.GetString("Ultimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Union Libre.
        /// </summary>
        public static string UnionLibre {
            get {
                return ResourceManager.GetString("UnionLibre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ventas.
        /// </summary>
        public static string Ventas {
            get {
                return ResourceManager.GetString("Ventas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Viudo.
        /// </summary>
        public static string Viudo {
            get {
                return ResourceManager.GetString("Viudo", resourceCulture);
            }
        }
    }
}
