//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WooW.Resources.ModelLabel {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WooW_ModelLabel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WooW_ModelLabel() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WooW.Resources.ModelLabel.WooW_ModelLabel", typeof(WooW_ModelLabel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrado Por.
        /// </summary>
        public static string BorradoPor {
            get {
                return ResourceManager.GetString("BorradoPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Causa de Borrado.
        /// </summary>
        public static string CausaDeBorrado {
            get {
                return ResourceManager.GetString("CausaDeBorrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Causa de Suspensión.
        /// </summary>
        public static string CausaDeSuspension {
            get {
                return ResourceManager.GetString("CausaDeSuspension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        public static string Correo {
            get {
                return ResourceManager.GetString("Correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creado Por.
        /// </summary>
        public static string CreadoPor {
            get {
                return ResourceManager.GetString("CreadoPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado Civil.
        /// </summary>
        public static string EstadoCivil {
            get {
                return ResourceManager.GetString("EstadoCivil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Borrado.
        /// </summary>
        public static string FechaDeBorrado {
            get {
                return ResourceManager.GetString("FechaDeBorrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Creación.
        /// </summary>
        public static string FechaDeCreacion {
            get {
                return ResourceManager.GetString("FechaDeCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Modificación.
        /// </summary>
        public static string FechaDeModificacion {
            get {
                return ResourceManager.GetString("FechaDeModificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Nacimiento.
        /// </summary>
        public static string FechaDeNacimiento {
            get {
                return ResourceManager.GetString("FechaDeNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Suspensión.
        /// </summary>
        public static string FechaDeSuspension {
            get {
                return ResourceManager.GetString("FechaDeSuspension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificado Por.
        /// </summary>
        public static string ModificadoPor {
            get {
                return ResourceManager.GetString("ModificadoPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salario.
        /// </summary>
        public static string Salario {
            get {
                return ResourceManager.GetString("Salario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suspendido Por.
        /// </summary>
        public static string SuspendidoPor {
            get {
                return ResourceManager.GetString("SuspendidoPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        public static string Telefono {
            get {
                return ResourceManager.GetString("Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiene Beneficios.
        /// </summary>
        public static string TieneBeneficios {
            get {
                return ResourceManager.GetString("TieneBeneficios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Empleado.
        /// </summary>
        public static string TipoDeEmpleado {
            get {
                return ResourceManager.GetString("TipoDeEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Empleado Desc..
        /// </summary>
        public static string TipoDeEmpleadoDesc {
            get {
                return ResourceManager.GetString("TipoDeEmpleadoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Versión en Db.
        /// </summary>
        public static string VersionEnDb {
            get {
                return ResourceManager.GetString("VersionEnDb", resourceCulture);
            }
        }
    }
}
