 
  
// ------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta. WooW.SB ttModeloRequestServicioCliente.tt
//     Versión del runtime: 1.0.0.0
//  
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
// ------------------------------------------------------------------------------//
using WooW.Core; 
using WooW.DTO;
using ServiceStack;

namespace WooW.Model
{
    public partial class WoSendMailMime
    {

        public static WoResponseGeneric Post(
            JsonApiClient Client, WoSendMailMime Request)
        {
            return Client.Post<WoResponseGeneric>(Request);
        }

        public static async Task<WoResponseGeneric> PostAsync(
            JsonApiClient Client, WoSendMailMime Request)
        {
            return await Client.PostAsync<WoResponseGeneric>(Request);
        }



    }
}
