// ------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta. WooW.SB ttCreateDB
//     Versión del runtime: 1.0.0.0
//  
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
// ------------------------------------------------------------------------------//
using ServiceStack.OrmLite;
using WooW.Model;
using System.Data;
using WooW.Core;
using WooW.Core.Common;


namespace WooW.Model;

public class CreateDB
{
    public static void Do(IDbConnection db, tWoIntanciaType IntanciaType, tWoDataBaseProviders DbProvider)
    {

        try
        {
            EmpleadoCreate.Do(db, IntanciaType, DbProvider);
        } 
        catch (Exception ex)
        {
            WoHelperDB.OnCreateExcepcion(db, IntanciaType, DbProvider, ex.Message);
        };        
        try
        {
            if (db.CreateTableIfNotExists<TipoDeEmpleado>()) {}
        } 
        catch (Exception ex)
        {
            WoHelperDB.OnCreateExcepcion(db, IntanciaType, DbProvider, ex.Message);
        };        
    }


    public static void DoForeignKey(IDbConnection db, tWoIntanciaType IntanciaType, tWoDataBaseProviders DbProvider)
    {

        try
        {
            db.AddForeignKey <Empleado, TipoDeEmpleado> (
                field: t => t.TipoDeEmpleadoId,
                foreignField: tr => tr.Id,
                onUpdate: OnFkOption.NoAction,
                onDelete: OnFkOption.NoAction,
                "FK_Empleado_TipoDeEmpleado_Id");
        }
        catch (Exception) { };

    }




}
