// ------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta. WooW.SB ttPermiso
//     Versión del runtime: 1.0.0.0
//  
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
// ------------------------------------------------------------------------------//
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Text;
using WooW.Core;
using WooW.Resources.Labels;

namespace WooW.Model
{
    public enum eWoProcess
    {
  
        [DescriptionAttribute(nameof(WooW_Label.Contabilidad))]
        CON
        ,
        [DescriptionAttribute(nameof(WooW_Label.Inventarios))]
        INV
        ,
        [DescriptionAttribute(nameof(WooW_Label.Sistema))]
        SYS
        ,
        [DescriptionAttribute(nameof(WooW_Label.SistemaDeAdministracionTributaria))]
        SAT
        ,
        [DescriptionAttribute(nameof(WooW_Label.DatosMaestros))]
        DAT
        ,
        [DescriptionAttribute(nameof(WooW_Label.CuentasPorCobrar))]
        CXC
        ,
        [DescriptionAttribute(nameof(WooW_Label.Compras))]
        COM
        ,
        [DescriptionAttribute(nameof(WooW_Label.Ventas))]
        VTA
        ,
        [DescriptionAttribute(nameof(WooW_Label.Facturacion))]
        FAC
        ,
        [DescriptionAttribute(nameof(WooW_Label.Tesoreria))]
        TES
        ,
        [DescriptionAttribute(nameof(WooW_Label.CuentasPorPagar))]
        CXP
    }


    public static class WoProcess
    {
        public static List<Tuple<eWoProcess, Type, WoTypeModel>> ProcessType = new List<Tuple<eWoProcess, Type, WoTypeModel>>()
        {
            { new Tuple<eWoProcess, Type, WoTypeModel>(eWoProcess.SYS, typeof(Empleado), WoTypeModel.Catalog) }
            , { new Tuple<eWoProcess, Type, WoTypeModel>(eWoProcess.SYS, typeof(TipoDeEmpleado), WoTypeModel.CatalogType) }
        };
    }
}
