// ------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta. WooW.SB ttPermiso
//     Versión del runtime: 1.0.0.0
//  
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
// ------------------------------------------------------------------------------//
using System.ComponentModel;
using WooW.Resources.Labels;

namespace WooW.Model 
{
    public enum Permiso
    {
  
        [DescriptionAttribute(nameof(WooW_Label.Lectura))]
        Lectura
        ,
        [DescriptionAttribute(nameof(WooW_Label.PuedeModificar))]
        PuedeModificar
        ,
        [DescriptionAttribute(nameof(WooW_Label.PuedeSuspender))]
        PuedeSuspender
        ,
        [DescriptionAttribute(nameof(WooW_Label.PuedeDarDeBaja))]
        PuedeDarDeBaja
        ,
        [DescriptionAttribute(nameof(WooW_Label.PuedeActivar))]
        PuedeActivar
        ,
        [DescriptionAttribute(nameof(WooW_Label.PuedeDarDeAlta))]
        PuedeDarDeAlta
        ,
        [DescriptionAttribute(nameof(WooW_Label.PuedeRegistrar))]
        PuedeRegistrar
        ,
        [DescriptionAttribute(nameof(WooW_Label.PuedeModificarRegistro))]
        PuedeModificarRegistro
        ,
        [DescriptionAttribute(nameof(WooW_Label.PuedeDescartar))]
        PuedeDescartar
        ,
        [DescriptionAttribute(nameof(WooW_Label.PuedeAfectarRegistro))]
        PuedeAfectarRegistro
        ,
        [DescriptionAttribute(nameof(WooW_Label.PuedeRegistrarYAfectar))]
        PuedeRegistrarYAfectar
        ,
        [DescriptionAttribute(nameof(WooW_Label.PuedeModificarDatosContables))]
        PuedeModificarDatosContables
        ,
        [DescriptionAttribute(nameof(WooW_Label.PuedeContabilizar))]
        PuedeContabilizar
        ,
        [DescriptionAttribute(nameof(WooW_Label.PuedeDescontabilizar))]
        PuedeDescontabilizar
        ,
        [DescriptionAttribute(nameof(WooW_Label.PuedeGenerarReportes))]
        PuedeGenerarReportes
        ,
        [DescriptionAttribute(nameof(WooW_Label.PuedeImportarDatos))]
        PuedeImportarDatos
        ,
        [DescriptionAttribute(nameof(WooW_Label.PuedeModificarParametros))]
        PuedeModificarParametros
        ,
        [DescriptionAttribute(nameof(WooW_Label.PuedeBorrar))]
        PuedeBorrar
    }
}
