// ------------------------------------------------------------------------------
// <auto-generated> 
//     Este código fue generado por una herramienta. WooW.SB ttModelo
//     Versión del runtime: 1.0.0.0
//  
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
// ------------------------------------------------------------------------------//
using System; 
using System.Runtime.Serialization;
using ServiceStack;
using ServiceStack.DataAnnotations;
using WooW.Core;
using WooW.Resources.Labels;
using WooW.Resources.ModelData;
using WooW.Resources.ModelLabel;
using WooW.Resources.ModelComment;
using Newtonsoft.Json;


#nullable disable

namespace WooW.Model
{



    //[WoLabel(Descripcion = nameof(WooW_Label.RespuestaGenerica))]
    [WoModelMeta(
        ProcesoId = "CON",
        TipoModelo = WoTypeModel.Response,
        Filtro = woGetListFilterType.Ninguno,
        Legacy  = "")]
    [JsonObject(MemberSerialization.OptOut)]
    public  partial class WoResponseGeneric 
    {
        public WoResponseGeneric()
        {
        }

        [Required]
        //[Description(nameof(WooW_ModelData.Respuesta))]
        //[WoLabelModel(Descripcion = nameof(WooW_ModelData.Respuesta),
        //   Formulario = nameof(WooW_ModelLabel.Respuesta),
        //   Grid = nameof(WooW_ModelLabel.Respuesta),
        //   Help = nameof(WooW_ModelComment.Respuesta))]
        [WoColumnMeta(
           Orden = 0,
           Longitud = 0,
           Precision = 0,
           TipoColumna = WoTypeColumn.Boolean,
           ModeloId = "",
           DescripcionLookUp = "",
           TipoDato = WoTypeData.Volatil,
           EsVisibleEnLookUp = false,
           Primaria = false,
           Nulo = false,
           Default = "",
           Legacy = "",
           TipoControl = WoTypeControl.Bool)]
                public bool Respuesta { get; set; }

        [Required]
        [StringLength(60)]
        //[Description(nameof(WooW_ModelData.Error))]
        //[WoLabelModel(Descripcion = nameof(WooW_ModelData.Error),
        //   Formulario = nameof(WooW_ModelLabel.Error),
        //   Grid = nameof(WooW_ModelLabel.Error),
        //   Help = nameof(WooW_ModelComment.Error))]
        [WoColumnMeta(
           Orden = 1,
           Longitud = 60,
           Precision = 0,
           TipoColumna = WoTypeColumn.String,
           ModeloId = "",
           DescripcionLookUp = "",
           TipoDato = WoTypeData.Volatil,
           EsVisibleEnLookUp = false,
           Primaria = false,
           Nulo = false,
           Default = "",
           Legacy = "",
           TipoControl = WoTypeControl.Text)]
                public string Error { get; set; }

        [Required]
        //[Description(nameof(WooW_ModelData.NumeroDeErrores))]
        //[WoLabelModel(Descripcion = nameof(WooW_ModelData.NumeroDeErrores),
        //   Formulario = nameof(WooW_ModelLabel.NumeroDeErrores),
        //   Grid = nameof(WooW_ModelLabel.NumeroDeErrores),
        //   Help = nameof(WooW_ModelComment.NumeroDeErrores))]
        [WoColumnMeta(
           Orden = 3,
           Longitud = 0,
           Precision = 0,
           TipoColumna = WoTypeColumn.Integer,
           ModeloId = "",
           DescripcionLookUp = "",
           TipoDato = WoTypeData.Volatil,
           EsVisibleEnLookUp = false,
           Primaria = false,
           Nulo = false,
           Default = "",
           Legacy = "",
           TipoControl = WoTypeControl.Spin)]
                public int NumeroErrores { get; set; }

    }
}
