 
  
// ------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta. WooW.SB ttModeloRequestServicioCliente.tt
//     Versión del runtime: 1.0.0.0
//  
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
// ------------------------------------------------------------------------------//
using WooW.Core; 
using ServiceStack;

namespace WooW.Model
{
    public partial class WoMenusReq
    {
        public static IList<WoMenusRes> Get(
            JsonApiClient Client, WoMenusReq Request)
        {
            return Client.Get<IList<WoMenusRes>>(Request);
        }

        public static async Task<IList<WoMenusRes>> GetAsync(
            JsonApiClient Client, WoMenusReq Request)
        {
            return await Client.GetAsync<IList<WoMenusRes>>(Request);
        }




    }
}
