// ------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta. WooW.SB ttModeloServicioRequest
//     Versión del runtime: 1.0.0.0
//  
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
// ------------------------------------------------------------------------------//
using WooW.Core.Server;
using WooW.Core;
using WooW.DTO;
using ServiceStack;
using ServiceStack.OrmLite;
using System.Collections.Generic;

namespace WooW.Model
{
    public partial class WoTransactionLog
    {


        public static IList<WoTransactionLogRes> Get(WoTargetConnection woTarget, WoTransactionLog Request)
        {
            WoTransactionLogScript Script = new WoTransactionLogScript();

            return Script.WoTransactionLogGet<WoTransactionLog, WoTransactionLogRes>(
                woTarget, Request);
        }




    }
}
