// ------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta. WooW.SB ttModeloDTO
//     Versión del runtime: 1.0.0.0
//  
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated> 
// ------------------------------------------------------------------------------//
using WooW.Core;
using WooW.Model;
using ServiceStack;
using ServiceStack.DataAnnotations;
using System.Collections.Generic;
using WooW.Resources.Labels;
using WooW.Resources.ModelData;
using WooW.Resources.ModelLabel;
using WooW.Resources.ModelComment;
using Newtonsoft.Json;

namespace WooW.DTO
{


#if DEBUG
#if SERVER
    [RequiresAnyRole(nameof(Rol.DatSup))]
#endif
    [ValidateIsAuthenticated]
    [Tag("Empleados")]
    [Route("/api/EmpleadoAutoQuery", "GET")]
    [JsonObject(MemberSerialization.OptOut)]
    public class EmpleadoAutoQuery : QueryDb<Empleado>, IWoInstanciaUdn
    {
    }
#endif

    #if SERVER
    [RequiresAnyRole(nameof(Rol.DatSup))]
    [AutoApply(Behavior.AuditQuery)]
    #endif
    [ValidateIsAuthenticated]
    [Tag("Empleados")]
    [Route("/api/EmpleadoList", "GET")]
    [JsonObject(MemberSerialization.OptOut)]
    public class EmpleadoList : IWoInstanciaUdn, IWoODataRequest
    {
        public string select { get; set; }
        public string filter { get; set; }
        public string orderby { get; set; }
        public bool count { get; set; }
        public int? top { get; set; }
        public int? skip { get; set; }
        public bool withref { get; set; }
        public string totalizer { get; set; }
    }

    #if SERVER
    [RequiresAnyRole(nameof(Rol.DatSup))]
    [AutoApply(Behavior.AuditQuery)]
    #endif
    [ValidateIsAuthenticated]
    [Tag("Empleados")]
    [Route("/api/EmpleadoGet", "GET")]
    [JsonObject(MemberSerialization.OptOut)]
    public class EmpleadoGet : IWoInstanciaUdn
    {
        public string Id { get; set; }
    }

    #if SERVER
    [RequiresAnyRole(nameof(Rol.DatSup))]
    [AutoApply(Behavior.AuditQuery)]
    #endif
    [ValidateIsAuthenticated]
    [Tag("Empleados")]
    [Route("/api/EmpleadoSingle", "GET")]
    [JsonObject(MemberSerialization.OptOut)]
    public class EmpleadoSingle : IWoInstanciaUdn
    {
        public string Id { get; set; }
    }


  
    #if SERVER
    [AutoApply(Behavior.AuditCreate)]
    [RequiresAnyRole(nameof(Rol.DatSup))]
    [RequiresAnyPermission(nameof(Permiso.PuedeDarDeAlta))]
    #endif
    [ValidateIsAuthenticated]
    [Tag("Empleados")]
    [Route("/api/EmpleadoNuevo", "POST")]
    [AutoPopulate(nameof(Empleado.WoState), Value = eEmpleado_WoState.Activo)]
    [WoModelBase(typeof(Empleado))]
    [JsonObject(MemberSerialization.OptOut)]
    public class EmpleadoNuevo : IWoInstanciaUdn, IReturn<Empleado>
    {
        public EmpleadoNuevo()
        {
  
        }

        [Required]
        [StringLength(12)]
        [Description(nameof(WooW_ModelData.Id))]
        [WoLabelModel(Descripcion = nameof(WooW_ModelData.Id),
           Formulario = nameof(WooW_ModelLabel.Id),
           Grid = nameof(WooW_ModelLabel.Id),
           Help = nameof(WooW_ModelComment.Id))]
        [WoColumnMeta(
           Orden = 2,
           Longitud = 12,
           Precision = 0,
           TipoColumna = WoTypeColumn.String,
           ModeloId = "",
           TipoDato = WoTypeData.Primary,
           EsVisibleEnLookUp = true,
           Primaria = true,
           Nulo = false,
           Default = "",
           Legacy = "",
           TipoControl = WoTypeControl.Text)]
        public string Id { get; set; }

        [Required]
        [StringLength(100)]
        [Description(nameof(WooW_ModelData.EsteCampoRepresentaElNombreCompletoDelEmpleadoIncluyendoTantoElNombreComoElApellido))]
        [WoLabelModel(Descripcion = nameof(WooW_ModelData.EsteCampoRepresentaElNombreCompletoDelEmpleadoIncluyendoTantoElNombreComoElApellido),
           Formulario = nameof(WooW_ModelLabel.Nombre),
           Grid = nameof(WooW_ModelLabel.Nombre),
           Help = nameof(WooW_ModelComment.EsteCampoRepresentaElNombreCompletoDelEmpleadoIncluyendoTantoElNombreComoElApellido))]
        [WoColumnMeta(
           Orden = 4,
           Longitud = 100,
           Precision = 0,
           TipoColumna = WoTypeColumn.String,
           ModeloId = "",
           TipoDato = WoTypeData.Volatil,
           EsVisibleEnLookUp = true,
           Primaria = false,
           Nulo = false,
           Default = "",
           Legacy = "",
           TipoControl = WoTypeControl.Text)]
        public string Nombre { get; set; }

        [Required]
        [Description(nameof(WooW_ModelData.EsteCampoAlmacenaLaFechaDeNacimientoDelEmpleado))]
        [WoLabelModel(Descripcion = nameof(WooW_ModelData.EsteCampoAlmacenaLaFechaDeNacimientoDelEmpleado),
           Formulario = nameof(WooW_ModelLabel.FechaDeNacimiento),
           Grid = nameof(WooW_ModelLabel.FechaDeNacimiento),
           Help = nameof(WooW_ModelComment.EsteCampoAlmacenaLaFechaDeNacimientoDelEmpleado))]
        [WoColumnMeta(
           Orden = 6,
           Longitud = 0,
           Precision = 0,
           TipoColumna = WoTypeColumn.Date,
           ModeloId = "",
           TipoDato = WoTypeData.Volatil,
           EsVisibleEnLookUp = false,
           Primaria = false,
           Nulo = false,
           Default = "",
           Legacy = "",
           TipoControl = WoTypeControl.Date)]
        public DateTime FechaDeNacimiento { get; set; }

        [Required]
        [Description(nameof(WooW_ModelData.EsteCampoIndicaElEstadoCivilDelEmpleado))]
        [WoLabelModel(Descripcion = nameof(WooW_ModelData.EsteCampoIndicaElEstadoCivilDelEmpleado),
           Formulario = nameof(WooW_ModelLabel.EstadoCivil),
           Grid = nameof(WooW_ModelLabel.EstadoCivil),
           Help = nameof(WooW_ModelComment.EsteCampoIndicaElEstadoCivilDelEmpleado))]
        [WoColumnMeta(
           Orden = 8,
           Longitud = 0,
           Precision = 0,
           TipoColumna = WoTypeColumn.EnumString,
           ModeloId = "",
           TipoDato = WoTypeData.Volatil,
           EsVisibleEnLookUp = false,
           Primaria = false,
           Nulo = false,
           Default = "",
           Legacy = "",
           TipoControl = WoTypeControl.EnumString)]
        public eEmpleado_EstadoCivil EstadoCivil { get; set; }

        [Required]
        [StringLength(100)]
        [Description(nameof(WooW_ModelData.EsteCampoAlmacenaLaDireccionDeCorreoElectronicoDelEmpleado))]
        [WoLabelModel(Descripcion = nameof(WooW_ModelData.EsteCampoAlmacenaLaDireccionDeCorreoElectronicoDelEmpleado),
           Formulario = nameof(WooW_ModelLabel.Correo),
           Grid = nameof(WooW_ModelLabel.Correo),
           Help = nameof(WooW_ModelComment.EsteCampoAlmacenaLaDireccionDeCorreoElectronicoDelEmpleado))]
        [WoColumnMeta(
           Orden = 10,
           Longitud = 100,
           Precision = 0,
           TipoColumna = WoTypeColumn.String,
           ModeloId = "",
           TipoDato = WoTypeData.Volatil,
           EsVisibleEnLookUp = false,
           Primaria = false,
           Nulo = false,
           Default = "",
           Legacy = "",
           TipoControl = WoTypeControl.TextMask)]
        public string Correo { get; set; }

        [Required]
        [StringLength(15)]
        [Description(nameof(WooW_ModelData.EsteCampoRepresentaElNumeroDeTelefonoDelEmpleado))]
        [WoLabelModel(Descripcion = nameof(WooW_ModelData.EsteCampoRepresentaElNumeroDeTelefonoDelEmpleado),
           Formulario = nameof(WooW_ModelLabel.Telefono),
           Grid = nameof(WooW_ModelLabel.Telefono),
           Help = nameof(WooW_ModelComment.EsteCampoRepresentaElNumeroDeTelefonoDelEmpleado))]
        [WoColumnMeta(
           Orden = 12,
           Longitud = 15,
           Precision = 0,
           TipoColumna = WoTypeColumn.String,
           ModeloId = "",
           TipoDato = WoTypeData.Volatil,
           EsVisibleEnLookUp = false,
           Primaria = false,
           Nulo = false,
           Default = "",
           Legacy = "",
           TipoControl = WoTypeControl.TextMask)]
        public string Telefono { get; set; }

        [Required]
        [DecimalLength(24,2)]
        [Description(nameof(WooW_ModelData.EsteCampoAlmacenaElSalarioMensualDelEmpleadoRepresentadoEnLaMonedaUtilizadaPorLaEmpresa))]
        [WoLabelModel(Descripcion = nameof(WooW_ModelData.EsteCampoAlmacenaElSalarioMensualDelEmpleadoRepresentadoEnLaMonedaUtilizadaPorLaEmpresa),
           Formulario = nameof(WooW_ModelLabel.Salario),
           Grid = nameof(WooW_ModelLabel.Salario),
           Help = nameof(WooW_ModelComment.EsteCampoAlmacenaElSalarioMensualDelEmpleadoRepresentadoEnLaMonedaUtilizadaPorLaEmpresa))]
        [WoColumnMeta(
           Orden = 14,
           Longitud = 24,
           Precision = 2,
           TipoColumna = WoTypeColumn.Decimal,
           ModeloId = "",
           TipoDato = WoTypeData.Volatil,
           EsVisibleEnLookUp = false,
           Primaria = false,
           Nulo = false,
           Default = "",
           Legacy = "",
           TipoControl = WoTypeControl.TextMask)]
        public decimal Salario { get; set; }

        [Required]
        [References(typeof(TipoDeEmpleado))]
        [Description(nameof(WooW_ModelData.TipoDeEmpleado))]
        [WoLabelModel(Descripcion = nameof(WooW_ModelData.TipoDeEmpleado),
           Formulario = nameof(WooW_ModelLabel.TipoDeEmpleado),
           Grid = nameof(WooW_ModelLabel.TipoDeEmpleado),
           Help = nameof(WooW_ModelComment.TipoDeEmpleado))]
        [WoColumnMeta(
           Orden = 16,
           Longitud = 0,
           Precision = 0,
           TipoColumna = WoTypeColumn.Reference,
           ModeloId = "TipoDeEmpleado",
           TipoDato = WoTypeData.Volatil,
           EsVisibleEnLookUp = false,
           Primaria = false,
           Nulo = false,
           Default = "",
           Legacy = "",
           TipoControl = WoTypeControl.LookUp)]
        public string TipoDeEmpleadoId { get; set; }

        [Required]
        [Description(nameof(WooW_ModelData.State))]
        [WoLabelModel(Descripcion = nameof(WooW_ModelData.State),
           Formulario = nameof(WooW_ModelLabel.State),
           Grid = nameof(WooW_ModelLabel.State),
           Help = nameof(WooW_ModelComment.State))]
        [WoColumnMeta(
           Orden = 200,
           Longitud = 0,
           Precision = 0,
           TipoColumna = WoTypeColumn.WoState,
           ModeloId = "",
           TipoDato = WoTypeData.Control,
           EsVisibleEnLookUp = false,
           Primaria = false,
           Nulo = false,
           Default = "",
           Legacy = "",
           TipoControl = WoTypeControl.WoState)]
        [WoNoEditar]
        public eEmpleado_WoState WoState { get; set; }


    }
  

  
    #if SERVER
    [AutoApply(Behavior.AuditModify)]
    [RequiresAnyRole(nameof(Rol.DatSup))]
    [RequiresAnyPermission(nameof(Permiso.PuedeActivar))]
    #endif
    [ValidateIsAuthenticated]
    [Tag("Empleados")]
    [Route("/api/EmpleadoActivar", "PUT PATCH")]
    [AutoPopulate(nameof(Empleado.WoState), Value = eEmpleado_WoState.Activo)]
    [WoModelBase(typeof(Empleado))]
    [JsonObject(MemberSerialization.OptOut)]
    public class EmpleadoActivar : IWoInstanciaUdn, IReturn<Empleado>
    {
        [Required]
        [StringLength(12)]
        [Description(nameof(WooW_ModelData.Id))]
        [WoLabelModel(Descripcion = nameof(WooW_ModelData.Id),
           Formulario = nameof(WooW_ModelLabel.Id),
           Grid = nameof(WooW_ModelLabel.Id),
           Help = nameof(WooW_ModelComment.Id))]
        [WoColumnMeta(
           Orden = 2,
           Longitud = 12,
           Precision = 0,
           TipoColumna = WoTypeColumn.String,
           ModeloId = "",
           TipoDato = WoTypeData.Primary,
           EsVisibleEnLookUp = true,
           Primaria = true,
           Nulo = false,
           Default = "",
           Legacy = "",
           TipoControl = WoTypeControl.Text)]
        [WoNoEditar]
        public string Id { get; set; }

        [Required]
        [Description(nameof(WooW_ModelData.State))]
        [WoLabelModel(Descripcion = nameof(WooW_ModelData.State),
           Formulario = nameof(WooW_ModelLabel.State),
           Grid = nameof(WooW_ModelLabel.State),
           Help = nameof(WooW_ModelComment.State))]
        [WoColumnMeta(
           Orden = 200,
           Longitud = 0,
           Precision = 0,
           TipoColumna = WoTypeColumn.WoState,
           ModeloId = "",
           TipoDato = WoTypeData.Control,
           EsVisibleEnLookUp = false,
           Primaria = false,
           Nulo = false,
           Default = "",
           Legacy = "",
           TipoControl = WoTypeControl.WoState)]
        [WoNoEditar]
        public eEmpleado_WoState? WoState { get; set; }

        [Required]
        [Description(nameof(WooW_ModelData.VersionEnDb))]
        [WoLabelModel(Descripcion = nameof(WooW_ModelData.VersionEnDb),
           Formulario = nameof(WooW_ModelLabel.VersionEnDb),
           Grid = nameof(WooW_ModelLabel.VersionEnDb),
           Help = nameof(WooW_ModelComment.VersionEnDb))]
        [WoColumnMeta(
           Orden = 201,
           Longitud = 0,
           Precision = 0,
           TipoColumna = WoTypeColumn.Long,
           ModeloId = "",
           TipoDato = WoTypeData.Control,
           EsVisibleEnLookUp = false,
           Primaria = false,
           Nulo = false,
           Default = "",
           Legacy = "",
           TipoControl = WoTypeControl.Spin)]
        [WoNoEditar]
        public ulong RowVersion { get; set; }


    }

  
    #if SERVER
    [AutoApply(Behavior.AuditModify)]
    [RequiresAnyRole(nameof(Rol.DatSup))]
    [RequiresAnyPermission(nameof(Permiso.PuedeSuspender))]
    #endif
    [ValidateIsAuthenticated]
    [Tag("Empleados")]
    [Route("/api/EmpleadoSuspender", "PUT PATCH")]
    [AutoPopulate(nameof(Empleado.WoState), Value = eEmpleado_WoState.Suspendido)]
    [WoModelBase(typeof(Empleado))]
    [JsonObject(MemberSerialization.OptOut)]
    public class EmpleadoSuspender : IWoInstanciaUdn, IReturn<Empleado>
    {
        [Required]
        [StringLength(12)]
        [Description(nameof(WooW_ModelData.Id))]
        [WoLabelModel(Descripcion = nameof(WooW_ModelData.Id),
           Formulario = nameof(WooW_ModelLabel.Id),
           Grid = nameof(WooW_ModelLabel.Id),
           Help = nameof(WooW_ModelComment.Id))]
        [WoColumnMeta(
           Orden = 2,
           Longitud = 12,
           Precision = 0,
           TipoColumna = WoTypeColumn.String,
           ModeloId = "",
           TipoDato = WoTypeData.Primary,
           EsVisibleEnLookUp = true,
           Primaria = true,
           Nulo = false,
           Default = "",
           Legacy = "",
           TipoControl = WoTypeControl.Text)]
        [WoNoEditar]
        public string Id { get; set; }

        [Required]
        [Description(nameof(WooW_ModelData.State))]
        [WoLabelModel(Descripcion = nameof(WooW_ModelData.State),
           Formulario = nameof(WooW_ModelLabel.State),
           Grid = nameof(WooW_ModelLabel.State),
           Help = nameof(WooW_ModelComment.State))]
        [WoColumnMeta(
           Orden = 200,
           Longitud = 0,
           Precision = 0,
           TipoColumna = WoTypeColumn.WoState,
           ModeloId = "",
           TipoDato = WoTypeData.Control,
           EsVisibleEnLookUp = false,
           Primaria = false,
           Nulo = false,
           Default = "",
           Legacy = "",
           TipoControl = WoTypeControl.WoState)]
        [WoNoEditar]
        public eEmpleado_WoState? WoState { get; set; }

        [Required]
        [Description(nameof(WooW_ModelData.VersionEnDb))]
        [WoLabelModel(Descripcion = nameof(WooW_ModelData.VersionEnDb),
           Formulario = nameof(WooW_ModelLabel.VersionEnDb),
           Grid = nameof(WooW_ModelLabel.VersionEnDb),
           Help = nameof(WooW_ModelComment.VersionEnDb))]
        [WoColumnMeta(
           Orden = 201,
           Longitud = 0,
           Precision = 0,
           TipoColumna = WoTypeColumn.Long,
           ModeloId = "",
           TipoDato = WoTypeData.Control,
           EsVisibleEnLookUp = false,
           Primaria = false,
           Nulo = false,
           Default = "",
           Legacy = "",
           TipoControl = WoTypeControl.Spin)]
        [WoNoEditar]
        public ulong RowVersion { get; set; }

        [StringLength(256)]
        [Description(nameof(WooW_ModelData.CausaDeSuspension))]
        [WoLabelModel(Descripcion = nameof(WooW_ModelData.CausaDeSuspension),
           Formulario = nameof(WooW_ModelLabel.CausaDeSuspension),
           Grid = nameof(WooW_ModelLabel.CausaDeSuspension),
           Help = nameof(WooW_ModelComment.CausaDeSuspension))]
        [WoColumnMeta(
           Orden = 210,
           Longitud = 256,
           Precision = 0,
           TipoColumna = WoTypeColumn.String,
           ModeloId = "",
           TipoDato = WoTypeData.Control,
           EsVisibleEnLookUp = false,
           Primaria = false,
           Nulo = true,
           Default = "",
           Legacy = "",
           TipoControl = WoTypeControl.Text)]
        public string SuspendInfo { get; set; }


    }

  
    #if SERVER
    [AutoApply(Behavior.AuditModify)]
    [RequiresAnyRole(nameof(Rol.DatSup))]
    [RequiresAnyPermission(nameof(Permiso.PuedeDarDeBaja))]
    #endif
    [ValidateIsAuthenticated]
    [Tag("Empleados")]
    [Route("/api/EmpleadoDarDeBaja", "PUT PATCH")]
    [AutoPopulate(nameof(Empleado.WoState), Value = eEmpleado_WoState.Baja)]
    [WoModelBase(typeof(Empleado))]
    [JsonObject(MemberSerialization.OptOut)]
    public class EmpleadoDarDeBaja : IWoInstanciaUdn, IReturn<Empleado>
    {
        [Required]
        [StringLength(12)]
        [Description(nameof(WooW_ModelData.Id))]
        [WoLabelModel(Descripcion = nameof(WooW_ModelData.Id),
           Formulario = nameof(WooW_ModelLabel.Id),
           Grid = nameof(WooW_ModelLabel.Id),
           Help = nameof(WooW_ModelComment.Id))]
        [WoColumnMeta(
           Orden = 2,
           Longitud = 12,
           Precision = 0,
           TipoColumna = WoTypeColumn.String,
           ModeloId = "",
           TipoDato = WoTypeData.Primary,
           EsVisibleEnLookUp = true,
           Primaria = true,
           Nulo = false,
           Default = "",
           Legacy = "",
           TipoControl = WoTypeControl.Text)]
        [WoNoEditar]
        public string Id { get; set; }

        [Required]
        [Description(nameof(WooW_ModelData.State))]
        [WoLabelModel(Descripcion = nameof(WooW_ModelData.State),
           Formulario = nameof(WooW_ModelLabel.State),
           Grid = nameof(WooW_ModelLabel.State),
           Help = nameof(WooW_ModelComment.State))]
        [WoColumnMeta(
           Orden = 200,
           Longitud = 0,
           Precision = 0,
           TipoColumna = WoTypeColumn.WoState,
           ModeloId = "",
           TipoDato = WoTypeData.Control,
           EsVisibleEnLookUp = false,
           Primaria = false,
           Nulo = false,
           Default = "",
           Legacy = "",
           TipoControl = WoTypeControl.WoState)]
        [WoNoEditar]
        public eEmpleado_WoState? WoState { get; set; }

        [Required]
        [Description(nameof(WooW_ModelData.VersionEnDb))]
        [WoLabelModel(Descripcion = nameof(WooW_ModelData.VersionEnDb),
           Formulario = nameof(WooW_ModelLabel.VersionEnDb),
           Grid = nameof(WooW_ModelLabel.VersionEnDb),
           Help = nameof(WooW_ModelComment.VersionEnDb))]
        [WoColumnMeta(
           Orden = 201,
           Longitud = 0,
           Precision = 0,
           TipoColumna = WoTypeColumn.Long,
           ModeloId = "",
           TipoDato = WoTypeData.Control,
           EsVisibleEnLookUp = false,
           Primaria = false,
           Nulo = false,
           Default = "",
           Legacy = "",
           TipoControl = WoTypeControl.Spin)]
        [WoNoEditar]
        public ulong RowVersion { get; set; }

        [StringLength(256)]
        [Description(nameof(WooW_ModelData.CausaDeBorrado))]
        [WoLabelModel(Descripcion = nameof(WooW_ModelData.CausaDeBorrado),
           Formulario = nameof(WooW_ModelLabel.CausaDeBorrado),
           Grid = nameof(WooW_ModelLabel.CausaDeBorrado),
           Help = nameof(WooW_ModelComment.CausaDeBorrado))]
        [WoColumnMeta(
           Orden = 225,
           Longitud = 256,
           Precision = 0,
           TipoColumna = WoTypeColumn.String,
           ModeloId = "",
           TipoDato = WoTypeData.Control,
           EsVisibleEnLookUp = false,
           Primaria = false,
           Nulo = true,
           Default = "",
           Legacy = "",
           TipoControl = WoTypeControl.Text)]
        public string DeleteInfo { get; set; }


    }

  
    #if SERVER
    [AutoApply(Behavior.AuditModify)]
    [RequiresAnyRole(nameof(Rol.DatSup))]
    [RequiresAnyPermission(nameof(Permiso.PuedeModificar))]
    #endif
    [ValidateIsAuthenticated]
    [Tag("Empleados")]
    [Route("/api/EmpleadoModificar", "PUT PATCH")]
    [AutoPopulate(nameof(Empleado.WoState), Value = eEmpleado_WoState.Activo)]
    [WoModelBase(typeof(Empleado))]
    [JsonObject(MemberSerialization.OptOut)]
    public class EmpleadoModificar : IWoInstanciaUdn, IReturn<Empleado>
    {
        [Required]
        [StringLength(12)]
        [Description(nameof(WooW_ModelData.Id))]
        [WoLabelModel(Descripcion = nameof(WooW_ModelData.Id),
           Formulario = nameof(WooW_ModelLabel.Id),
           Grid = nameof(WooW_ModelLabel.Id),
           Help = nameof(WooW_ModelComment.Id))]
        [WoColumnMeta(
           Orden = 2,
           Longitud = 12,
           Precision = 0,
           TipoColumna = WoTypeColumn.String,
           ModeloId = "",
           TipoDato = WoTypeData.Primary,
           EsVisibleEnLookUp = true,
           Primaria = true,
           Nulo = false,
           Default = "",
           Legacy = "",
           TipoControl = WoTypeControl.Text)]
        [WoNoEditar]
        public string Id { get; set; }

        [Required]
        [StringLength(100)]
        [Description(nameof(WooW_ModelData.EsteCampoRepresentaElNombreCompletoDelEmpleadoIncluyendoTantoElNombreComoElApellido))]
        [WoLabelModel(Descripcion = nameof(WooW_ModelData.EsteCampoRepresentaElNombreCompletoDelEmpleadoIncluyendoTantoElNombreComoElApellido),
           Formulario = nameof(WooW_ModelLabel.Nombre),
           Grid = nameof(WooW_ModelLabel.Nombre),
           Help = nameof(WooW_ModelComment.EsteCampoRepresentaElNombreCompletoDelEmpleadoIncluyendoTantoElNombreComoElApellido))]
        [WoColumnMeta(
           Orden = 4,
           Longitud = 100,
           Precision = 0,
           TipoColumna = WoTypeColumn.String,
           ModeloId = "",
           TipoDato = WoTypeData.Volatil,
           EsVisibleEnLookUp = true,
           Primaria = false,
           Nulo = false,
           Default = "",
           Legacy = "",
           TipoControl = WoTypeControl.Text)]
        public string Nombre { get; set; }

        [Required]
        [Description(nameof(WooW_ModelData.EsteCampoAlmacenaLaFechaDeNacimientoDelEmpleado))]
        [WoLabelModel(Descripcion = nameof(WooW_ModelData.EsteCampoAlmacenaLaFechaDeNacimientoDelEmpleado),
           Formulario = nameof(WooW_ModelLabel.FechaDeNacimiento),
           Grid = nameof(WooW_ModelLabel.FechaDeNacimiento),
           Help = nameof(WooW_ModelComment.EsteCampoAlmacenaLaFechaDeNacimientoDelEmpleado))]
        [WoColumnMeta(
           Orden = 6,
           Longitud = 0,
           Precision = 0,
           TipoColumna = WoTypeColumn.Date,
           ModeloId = "",
           TipoDato = WoTypeData.Volatil,
           EsVisibleEnLookUp = false,
           Primaria = false,
           Nulo = false,
           Default = "",
           Legacy = "",
           TipoControl = WoTypeControl.Date)]
        public DateTime? FechaDeNacimiento { get; set; }

        [Required]
        [Description(nameof(WooW_ModelData.EsteCampoIndicaElEstadoCivilDelEmpleado))]
        [WoLabelModel(Descripcion = nameof(WooW_ModelData.EsteCampoIndicaElEstadoCivilDelEmpleado),
           Formulario = nameof(WooW_ModelLabel.EstadoCivil),
           Grid = nameof(WooW_ModelLabel.EstadoCivil),
           Help = nameof(WooW_ModelComment.EsteCampoIndicaElEstadoCivilDelEmpleado))]
        [WoColumnMeta(
           Orden = 8,
           Longitud = 0,
           Precision = 0,
           TipoColumna = WoTypeColumn.EnumString,
           ModeloId = "",
           TipoDato = WoTypeData.Volatil,
           EsVisibleEnLookUp = false,
           Primaria = false,
           Nulo = false,
           Default = "",
           Legacy = "",
           TipoControl = WoTypeControl.EnumString)]
        public eEmpleado_EstadoCivil EstadoCivil { get; set; }

        [Required]
        [StringLength(100)]
        [Description(nameof(WooW_ModelData.EsteCampoAlmacenaLaDireccionDeCorreoElectronicoDelEmpleado))]
        [WoLabelModel(Descripcion = nameof(WooW_ModelData.EsteCampoAlmacenaLaDireccionDeCorreoElectronicoDelEmpleado),
           Formulario = nameof(WooW_ModelLabel.Correo),
           Grid = nameof(WooW_ModelLabel.Correo),
           Help = nameof(WooW_ModelComment.EsteCampoAlmacenaLaDireccionDeCorreoElectronicoDelEmpleado))]
        [WoColumnMeta(
           Orden = 10,
           Longitud = 100,
           Precision = 0,
           TipoColumna = WoTypeColumn.String,
           ModeloId = "",
           TipoDato = WoTypeData.Volatil,
           EsVisibleEnLookUp = false,
           Primaria = false,
           Nulo = false,
           Default = "",
           Legacy = "",
           TipoControl = WoTypeControl.TextMask)]
        public string Correo { get; set; }

        [Required]
        [StringLength(15)]
        [Description(nameof(WooW_ModelData.EsteCampoRepresentaElNumeroDeTelefonoDelEmpleado))]
        [WoLabelModel(Descripcion = nameof(WooW_ModelData.EsteCampoRepresentaElNumeroDeTelefonoDelEmpleado),
           Formulario = nameof(WooW_ModelLabel.Telefono),
           Grid = nameof(WooW_ModelLabel.Telefono),
           Help = nameof(WooW_ModelComment.EsteCampoRepresentaElNumeroDeTelefonoDelEmpleado))]
        [WoColumnMeta(
           Orden = 12,
           Longitud = 15,
           Precision = 0,
           TipoColumna = WoTypeColumn.String,
           ModeloId = "",
           TipoDato = WoTypeData.Volatil,
           EsVisibleEnLookUp = false,
           Primaria = false,
           Nulo = false,
           Default = "",
           Legacy = "",
           TipoControl = WoTypeControl.TextMask)]
        public string Telefono { get; set; }

        [Required]
        [DecimalLength(24,2)]
        [Description(nameof(WooW_ModelData.EsteCampoAlmacenaElSalarioMensualDelEmpleadoRepresentadoEnLaMonedaUtilizadaPorLaEmpresa))]
        [WoLabelModel(Descripcion = nameof(WooW_ModelData.EsteCampoAlmacenaElSalarioMensualDelEmpleadoRepresentadoEnLaMonedaUtilizadaPorLaEmpresa),
           Formulario = nameof(WooW_ModelLabel.Salario),
           Grid = nameof(WooW_ModelLabel.Salario),
           Help = nameof(WooW_ModelComment.EsteCampoAlmacenaElSalarioMensualDelEmpleadoRepresentadoEnLaMonedaUtilizadaPorLaEmpresa))]
        [WoColumnMeta(
           Orden = 14,
           Longitud = 24,
           Precision = 2,
           TipoColumna = WoTypeColumn.Decimal,
           ModeloId = "",
           TipoDato = WoTypeData.Volatil,
           EsVisibleEnLookUp = false,
           Primaria = false,
           Nulo = false,
           Default = "",
           Legacy = "",
           TipoControl = WoTypeControl.TextMask)]
        public decimal? Salario { get; set; }

        [Required]
        [References(typeof(TipoDeEmpleado))]
        [Description(nameof(WooW_ModelData.TipoDeEmpleado))]
        [WoLabelModel(Descripcion = nameof(WooW_ModelData.TipoDeEmpleado),
           Formulario = nameof(WooW_ModelLabel.TipoDeEmpleado),
           Grid = nameof(WooW_ModelLabel.TipoDeEmpleado),
           Help = nameof(WooW_ModelComment.TipoDeEmpleado))]
        [WoColumnMeta(
           Orden = 16,
           Longitud = 0,
           Precision = 0,
           TipoColumna = WoTypeColumn.Reference,
           ModeloId = "TipoDeEmpleado",
           TipoDato = WoTypeData.Volatil,
           EsVisibleEnLookUp = false,
           Primaria = false,
           Nulo = false,
           Default = "",
           Legacy = "",
           TipoControl = WoTypeControl.LookUp)]
        public string TipoDeEmpleadoId { get; set; }

        [Required]
        [Description(nameof(WooW_ModelData.State))]
        [WoLabelModel(Descripcion = nameof(WooW_ModelData.State),
           Formulario = nameof(WooW_ModelLabel.State),
           Grid = nameof(WooW_ModelLabel.State),
           Help = nameof(WooW_ModelComment.State))]
        [WoColumnMeta(
           Orden = 200,
           Longitud = 0,
           Precision = 0,
           TipoColumna = WoTypeColumn.WoState,
           ModeloId = "",
           TipoDato = WoTypeData.Control,
           EsVisibleEnLookUp = false,
           Primaria = false,
           Nulo = false,
           Default = "",
           Legacy = "",
           TipoControl = WoTypeControl.WoState)]
        [WoNoEditar]
        public eEmpleado_WoState? WoState { get; set; }

        [Required]
        [Description(nameof(WooW_ModelData.VersionEnDb))]
        [WoLabelModel(Descripcion = nameof(WooW_ModelData.VersionEnDb),
           Formulario = nameof(WooW_ModelLabel.VersionEnDb),
           Grid = nameof(WooW_ModelLabel.VersionEnDb),
           Help = nameof(WooW_ModelComment.VersionEnDb))]
        [WoColumnMeta(
           Orden = 201,
           Longitud = 0,
           Precision = 0,
           TipoColumna = WoTypeColumn.Long,
           ModeloId = "",
           TipoDato = WoTypeData.Control,
           EsVisibleEnLookUp = false,
           Primaria = false,
           Nulo = false,
           Default = "",
           Legacy = "",
           TipoControl = WoTypeControl.Spin)]
        [WoNoEditar]
        public ulong RowVersion { get; set; }


    }

  

  
#if SERVER
    [RequiresAnyRole(nameof(Rol.DatSup))]
    [RequiresAnyPermission(nameof(Permiso.PuedeBorrar))]
#endif
    [ValidateIsAuthenticated]
    [Tag("Empleados")]
    [Route("/api/EmpleadoBorrar", "DELETE")]
    [JsonObject(MemberSerialization.OptOut)]
    public class EmpleadoBorrar : IWoInstanciaUdn, IReturn<Empleado>
    {
        public string Id { get; set; }
    }
  
}
