// ------------------------------------------------------------------------------
// <auto-generated> 
//     Este código fue generado por una herramienta. WooW.SB ttModelo
//     Versión del runtime: 1.0.0.0
//  
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
// ------------------------------------------------------------------------------//
using System; 
using System.Runtime.Serialization;
using ServiceStack;
using ServiceStack.DataAnnotations;
using WooW.Core;
using WooW.Resources.Labels;
using WooW.Resources.ModelData;
using WooW.Resources.ModelLabel;
using WooW.Resources.ModelComment;
using Newtonsoft.Json;


#nullable disable

namespace WooW.Model
{



    //[WoLabel(Descripcion = nameof(WooW_Label.RolesYPermisos))]
    [WoModelMeta(
        ProcesoId = "SYS",
        TipoModelo = WoTypeModel.Response,
        Filtro = woGetListFilterType.Ninguno,
        Legacy  = "")]
    [JsonObject(MemberSerialization.OptOut)]
    public  partial class WoRolePermissionRes 
    {
        public WoRolePermissionRes()
        {


        }

        [Required]
        [StringLength(256)]
        //[Description(nameof(WooW_ModelData.Rol))]
        //[WoLabelModel(Descripcion = nameof(WooW_ModelData.Rol),
        //   Formulario = nameof(WooW_ModelLabel.Rol),
        //   Grid = nameof(WooW_ModelLabel.Rol),
        //   Help = nameof(WooW_ModelComment.Rol))]
        [WoColumnMeta(
           Orden = 0,
           Longitud = 256,
           Precision = 0,
           TipoColumna = WoTypeColumn.String,
           ModeloId = "",
           DescripcionLookUp = "",
           TipoDato = WoTypeData.Volatil,
           EsVisibleEnLookUp = false,
           Primaria = false,
           Nulo = false,
           Default = "",
           Legacy = "",
           TipoControl = WoTypeControl.Text)]
                public virtual IList <string> RoleCol { get; set; }

        [Required]
        [StringLength(256)]
        //[Description(nameof(WooW_ModelData.Permiso))]
        //[WoLabelModel(Descripcion = nameof(WooW_ModelData.Permiso),
        //   Formulario = nameof(WooW_ModelLabel.Permiso),
        //   Grid = nameof(WooW_ModelLabel.Permiso),
        //   Help = nameof(WooW_ModelComment.Permiso))]
        [WoColumnMeta(
           Orden = 1,
           Longitud = 256,
           Precision = 0,
           TipoColumna = WoTypeColumn.String,
           ModeloId = "",
           DescripcionLookUp = "",
           TipoDato = WoTypeData.Volatil,
           EsVisibleEnLookUp = false,
           Primaria = false,
           Nulo = false,
           Default = "",
           Legacy = "",
           TipoControl = WoTypeControl.Text)]
                public virtual IList <string> PermissionCol { get; set; }

    }
}
