 
  
// ------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta. WooW.SB ttModeloRequestServicioCliente.tt
//     Versión del runtime: 1.0.0.0
//  
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
// ------------------------------------------------------------------------------//
using WooW.Core; 
using WooW.DTO;
using ServiceStack;

namespace WooW.Model
{
    public partial class WoTransactionLog
    {
        public static IList<WoTransactionLogRes> Get(
            JsonApiClient Client, WoTransactionLog Request)
        {
            return Client.Get<IList<WoTransactionLogRes>>(Request);
        }

        public static async Task<IList<WoTransactionLogRes>> GetAsync(
            JsonApiClient Client, WoTransactionLog Request)
        {
            return await Client.GetAsync<IList<WoTransactionLogRes>>(Request);
        }




    }
}
