// ------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta. WooW.SB ttModeloServicioRequest
//     Versión del runtime: 1.0.0.0
//  
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
// ------------------------------------------------------------------------------//
using WooW.Core.Server;
using WooW.Core;
using WooW.DTO;
using ServiceStack;
using ServiceStack.OrmLite;
using System.Collections.Generic;

namespace WooW.Model
{
    public partial class WoReportReq
    {


        public static WoReportRes Get(WoTargetConnection woTarget, WoReportReq Request)
        {
            WoReportReqScript Script = new WoReportReqScript();

            return Script.WoReportReqGet<WoReportReq, WoReportRes>(
                woTarget, Request);
        }




    }
}
