// ------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta. WooW.SB ttRol
//     Versión del runtime: 1.0.0.0
//  
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
// ------------------------------------------------------------------------------//
using System.ComponentModel;
using WooW.Resources.Labels;
namespace WooW.Model
{
    public enum Rol
    {
  
        [DescriptionAttribute(nameof(WooW_Label.SupervisorDeInventario))]
        InvSup
        ,
        [DescriptionAttribute(nameof(WooW_Label.AuxiliarDeInventario))]
        InvAux
        ,
        [DescriptionAttribute(nameof(WooW_Label.SupervisorDeContabilidad))]
        ConSup
        ,
        [DescriptionAttribute(nameof(WooW_Label.AuxiliarDeContabilidad))]
        ConAux
        ,
        [DescriptionAttribute(nameof(WooW_Label.AdministradorDeDatosMaestros))]
        DatSup
        ,
        [DescriptionAttribute(nameof(WooW_Label.AuxiliarDeDatosMaestros))]
        DatAux
        ,
        [DescriptionAttribute(nameof(WooW_Label.AdministradorDelSistema))]
        AdmSis
        ,
        [DescriptionAttribute(nameof(WooW_Label.AuxiliarDeNomina))]
        NomAux
        ,
        [DescriptionAttribute(nameof(WooW_Label.SupervisorDeNomina))]
        NomSup
        ,
        [DescriptionAttribute(nameof(WooW_Label.AuxiliarDeCompras))]
        ComAux
        ,
        [DescriptionAttribute(nameof(WooW_Label.SupervisorDeCompras))]
        ComSup
        ,
        [DescriptionAttribute(nameof(WooW_Label.SupervisorDeFacturacion))]
        FacSup
        ,
        [DescriptionAttribute(nameof(WooW_Label.AuxiliarDeFacturacion))]
        FacAux
        ,
        [DescriptionAttribute(nameof(WooW_Label.SupervisorDeCuentasPorCobrar))]
        CxcSup
        ,
        [DescriptionAttribute(nameof(WooW_Label.AuxiliarDeCuentasPorCobrar))]
        CxcAux
        ,
        [DescriptionAttribute(nameof(WooW_Label.SupervisorDeTesoreria))]
        TesSup
        ,
        [DescriptionAttribute(nameof(WooW_Label.AuxiliarDeTesoreria))]
        TesAux
        ,
        [DescriptionAttribute(nameof(WooW_Label.SupervisorDeCuentasPorPagar))]
        CxpSup
        ,
        [DescriptionAttribute(nameof(WooW_Label.AuxiliarDeCuentasPorPagar))]
        CxpAux
    }
}
