// ------------------------------------------------------------------------------
// <auto-generated> 
//     Este código fue generado por una herramienta. WooW.SB ttModelo
//     Versión del runtime: 1.0.0.0
//  
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
// ------------------------------------------------------------------------------//
using System; 
using System.Runtime.Serialization;
using ServiceStack;
using ServiceStack.DataAnnotations;
using WooW.Core;
using WooW.Resources.Labels;
using WooW.Resources.ModelData;
using WooW.Resources.ModelLabel;
using WooW.Resources.ModelComment;
using Newtonsoft.Json;


#nullable disable

namespace WooW.Model
{




//    #if SERVER
//    [AutoApply(Behavior.AuditQuery)]
//#endif
    [ValidateIsAuthenticated]
    [Tag("WoIntrinsic")]
    [Route("/api/WoTransactionLog", "GET")]
    ////[WoLabel(Descripcion = nameof(WooW_Label.LogDeTransaccion))]
    //[WoModelMeta(
    //    ProcesoId = "SYS",
    //    TipoModelo = WoTypeModel.Request,
    //    Filtro = woGetListFilterType.Ninguno,
    //    Legacy  = "")]
    //[JsonObject(MemberSerialization.OptOut)]
    public  partial class WoTransactionLog : IWoInstanciaUdn
    {
        public WoTransactionLog()
        {
        }

        [Required]
        [StringLength(200)]
        //[Description(nameof(WooW_ModelData.Model))]
        //[WoLabelModel(Descripcion = nameof(WooW_ModelData.Model),
        //   Formulario = nameof(WooW_ModelLabel.Model),
        //   Grid = nameof(WooW_ModelLabel.Model),
        //   Help = nameof(WooW_ModelComment.Model))]
        [WoColumnMeta(
           Orden = 0,
           Longitud = 200,
           Precision = 0,
           TipoColumna = WoTypeColumn.String,
           ModeloId = "",
           DescripcionLookUp = "",
           TipoDato = WoTypeData.Volatil,
           EsVisibleEnLookUp = false,
           Primaria = false,
           Nulo = false,
           Default = "",
           Legacy = "",
           TipoControl = WoTypeControl.Text)]
                public string Model { get; set; }

        [Required]
        [StringLength(60)]
        //[Description(nameof(WooW_ModelData.ModelId))]
        //[WoLabelModel(Descripcion = nameof(WooW_ModelData.ModelId),
        //   Formulario = nameof(WooW_ModelLabel.ModelId),
        //   Grid = nameof(WooW_ModelLabel.ModelId),
        //   Help = nameof(WooW_ModelComment.ModelId))]
        [WoColumnMeta(
           Orden = 1,
           Longitud = 60,
           Precision = 0,
           TipoColumna = WoTypeColumn.String,
           ModeloId = "",
           DescripcionLookUp = "",
           TipoDato = WoTypeData.Volatil,
           EsVisibleEnLookUp = false,
           Primaria = false,
           Nulo = false,
           Default = "",
           Legacy = "",
           TipoControl = WoTypeControl.Text)]
                public string ModelId { get; set; }

    }
}
