// ------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta. WooW.SB ttModeloServicio
//     Versión del runtime: 1.0.0.0
//  
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
// ------------------------------------------------------------------------------//
using WooW.Core.Server;
using WooW.Core;
using WooW.Core.Common;
using WooW.DTO;
using ServiceStack;
using ServiceStack.OrmLite;
using System.Collections.Generic;

namespace WooW.Model
{
    public partial class Banco
    {

        public static WoODataResponse<Banco> List(WoTargetConnection woTarget, BancoList ODataRequest)
        {
            return WoGenericService.ODataGet<Banco>(woTarget, ODataRequest, true);
        }


        public static Banco Get(WoTargetConnection woTarget, BancoGet GetRequest, WoGetFlags woGetFlags)
        {
            return Banco.Get(woTarget, (string)GetRequest.GetObjectId(), woGetFlags | WoGetFlags.ApplyFilter );
        }  

        public static Banco Get(WoTargetConnection woTarget, BancoGet GetRequest)
        {
            return Banco.Get(woTarget, (string)GetRequest.GetObjectId(), WoGetFlags.None | WoGetFlags.ApplyFilter);
        }  

        public static Banco Get(WoTargetConnection woTarget, string Id)
        {
            return Banco.Get(woTarget, Id, WoGetFlags.None | WoGetFlags.ApplyFilter);
        }

        public static Banco Get(WoTargetConnection woTarget, string Id, WoGetFlags woGetFlags)
        {
            return WoGenericService.Get<Banco>(woTarget, Id, woGetFlags | WoGetFlags.ApplyFilter);
        }

        public static Banco GetCheck(WoTargetConnection woTarget, string Id)
        {
            return WoGenericService.GetCheckIfNullThenExcept<Banco>(woTarget, Id, WoGetFlags.None | WoGetFlags.ApplyFilter);
        }

        public static Banco Single(WoTargetConnection woTarget, BancoSingle SingleRequest, WoGetFlags woGetFlags)
        {
            return Banco.Single(woTarget, (string)SingleRequest.GetObjectId(), woGetFlags | WoGetFlags.ApplyFilter);
        }  

        public static Banco Single(WoTargetConnection woTarget, BancoSingle SingleRequest)
        {
            return Banco.Single(woTarget, (string)SingleRequest.GetObjectId(), WoGetFlags.None | WoGetFlags.ApplyFilter);
        }  

        public static Banco Single(WoTargetConnection woTarget, string Id)
        {
            return Banco.Single(woTarget, Id, WoGetFlags.None | WoGetFlags.ApplyFilter);
        }

        public static Banco Single(WoTargetConnection woTarget, string Id, WoGetFlags woGetFlags)
        {
            return WoGenericService.Single<Banco>(woTarget, Id, woGetFlags | WoGetFlags.ApplyFilter);
        }

        public static Banco SingleCheck(WoTargetConnection woTarget, string Id)
        {
            return WoGenericService.SingleCheckIfNullThenExcept<Banco>(woTarget, Id, WoGetFlags.None | WoGetFlags.ApplyFilter);
        }


        public static Banco Post(WoTargetConnection woTarget, BancoNuevo dtoRequest)
        {


            return WoGenericServiceCatalog.Post<BancoNuevo, Banco>(woTarget, dtoRequest,
                (int)eBanco_WoState.Activo,
                null,
                null);
        }
        public static Banco Put(WoTargetConnection woTarget, BancoActivar dtoRequest)
        {


            return WoGenericServiceCatalog.PutPatch<BancoActivar, Banco>(woTarget, dtoRequest, woModifyVerb.Put,
                (int)eBanco_WoState.Suspendido, (int)eBanco_WoState.Activo,
                null,
                null);
        }

        public static Banco Patch(WoTargetConnection woTarget, BancoActivar dtoRequest)
        {


            return WoGenericServiceCatalog.PutPatch<BancoActivar, Banco>(woTarget, dtoRequest, woModifyVerb.Patch,
                (int)eBanco_WoState.Suspendido, (int)eBanco_WoState.Activo,
                null,
                null);
        }

        public static Banco Put(WoTargetConnection woTarget, BancoSuspender dtoRequest)
        {


            return WoGenericServiceCatalog.PutPatch<BancoSuspender, Banco>(woTarget, dtoRequest, woModifyVerb.Put,
                (int)eBanco_WoState.Activo, (int)eBanco_WoState.Suspendido,
                null,
                null);
        }

        public static Banco Patch(WoTargetConnection woTarget, BancoSuspender dtoRequest)
        {


            return WoGenericServiceCatalog.PutPatch<BancoSuspender, Banco>(woTarget, dtoRequest, woModifyVerb.Patch,
                (int)eBanco_WoState.Activo, (int)eBanco_WoState.Suspendido,
                null,
                null);
        }

        public static Banco SoftDelete(WoTargetConnection woTarget, BancoDarDeBaja dtoRequest)
        {


            return WoGenericServiceCatalog.SoftDelete<BancoDarDeBaja, Banco>(woTarget, dtoRequest,
                (int)eBanco_WoState.Suspendido, (int)eBanco_WoState.Baja,
                null,
                null);
        }
        public static Banco Put(WoTargetConnection woTarget, BancoModificar dtoRequest)
        {


            return WoGenericServiceCatalog.PutPatch<BancoModificar, Banco>(woTarget, dtoRequest, woModifyVerb.Put,
                (int)eBanco_WoState.Activo, (int)eBanco_WoState.Activo,
                null,
                null);
        }

        public static Banco Patch(WoTargetConnection woTarget, BancoModificar dtoRequest)
        {


            return WoGenericServiceCatalog.PutPatch<BancoModificar, Banco>(woTarget, dtoRequest, woModifyVerb.Patch,
                (int)eBanco_WoState.Activo, (int)eBanco_WoState.Activo,
                null,
                null);
        }



        public static Banco Delete(WoTargetConnection woTarget, string id)
        {
            return Banco.Delete(woTarget,
                new BancoBorrar()
                {
                    Id = id
                }
            );
        }

        public static Banco Delete(WoTargetConnection woTarget, BancoBorrar dtoRequest)
        {

            return WoGenericServiceCatalog.Delete<BancoBorrar, Banco>(woTarget,
                dtoRequest,
                null
            );
        }
  
    }
}
