//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WooW.Resources.ModelComment {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WooW_ModelComment {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WooW_ModelComment() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WooW.Resources.ModelComment.WooW_ModelComment", typeof(WooW_ModelComment).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrado Por.
        /// </summary>
        public static string BorradoPor {
            get {
                return ResourceManager.GetString("BorradoPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Causa de Borrado.
        /// </summary>
        public static string CausaDeBorrado {
            get {
                return ResourceManager.GetString("CausaDeBorrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Causa de Suspensión.
        /// </summary>
        public static string CausaDeSuspension {
            get {
                return ResourceManager.GetString("CausaDeSuspension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creado Por.
        /// </summary>
        public static string CreadoPor {
            get {
                return ResourceManager.GetString("CreadoPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este campo almacena el salario mensual del empleado, representado en la moneda utilizada por la empresa.
        /// </summary>
        public static string EsteCampoAlmacenaElSalarioMensualDelEmpleadoRepresentadoEnLaMonedaUtilizadaPorLaEmpresa {
            get {
                return ResourceManager.GetString("EsteCampoAlmacenaElSalarioMensualDelEmpleadoRepresentadoEnLaMonedaUtilizadaPorLaE" +
                        "mpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este campo almacena la dirección de correo electrónico del empleado.
        /// </summary>
        public static string EsteCampoAlmacenaLaDireccionDeCorreoElectronicoDelEmpleado {
            get {
                return ResourceManager.GetString("EsteCampoAlmacenaLaDireccionDeCorreoElectronicoDelEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este campo almacena la fecha de nacimiento del empleado.
        /// </summary>
        public static string EsteCampoAlmacenaLaFechaDeNacimientoDelEmpleado {
            get {
                return ResourceManager.GetString("EsteCampoAlmacenaLaFechaDeNacimientoDelEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este campo indica el estado civil del empleado.
        /// </summary>
        public static string EsteCampoIndicaElEstadoCivilDelEmpleado {
            get {
                return ResourceManager.GetString("EsteCampoIndicaElEstadoCivilDelEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este campo indica si el tipo de empleado tiene acceso a beneficios adicionales como seguro médico, vacaciones pagadas, bonos, etc..
        /// </summary>
        public static string EsteCampoIndicaSiElTipoDeEmpleadoTieneAccesoABeneficiosAdicionalesComoSeguroMedicoVacacionesPagadasBonosEtc {
            get {
                return ResourceManager.GetString("EsteCampoIndicaSiElTipoDeEmpleadoTieneAccesoABeneficiosAdicionalesComoSeguroMedic" +
                        "oVacacionesPagadasBonosEtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este campo proporciona una descripción detallada del tipo de empleado.
        /// </summary>
        public static string EsteCampoProporcionaUnaDescripcionDetalladaDelTipoDeEmpleado {
            get {
                return ResourceManager.GetString("EsteCampoProporcionaUnaDescripcionDetalladaDelTipoDeEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este campo representa el nombre completo del empleado, incluyendo tanto el nombre como el apellido.
        /// </summary>
        public static string EsteCampoRepresentaElNombreCompletoDelEmpleadoIncluyendoTantoElNombreComoElApellido {
            get {
                return ResourceManager.GetString("EsteCampoRepresentaElNombreCompletoDelEmpleadoIncluyendoTantoElNombreComoElApelli" +
                        "do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este campo representa el número de teléfono del empleado.
        /// </summary>
        public static string EsteCampoRepresentaElNumeroDeTelefonoDelEmpleado {
            get {
                return ResourceManager.GetString("EsteCampoRepresentaElNumeroDeTelefonoDelEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este campo representa la descripción corta del tipo de empleado.
        /// </summary>
        public static string EsteCampoRepresentaLaDescripcionCortaDelTipoDeEmpleado {
            get {
                return ResourceManager.GetString("EsteCampoRepresentaLaDescripcionCortaDelTipoDeEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Borrado.
        /// </summary>
        public static string FechaDeBorrado {
            get {
                return ResourceManager.GetString("FechaDeBorrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Creación.
        /// </summary>
        public static string FechaDeCreacion {
            get {
                return ResourceManager.GetString("FechaDeCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Modificación.
        /// </summary>
        public static string FechaDeModificacion {
            get {
                return ResourceManager.GetString("FechaDeModificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Suspensión.
        /// </summary>
        public static string FechaDeSuspension {
            get {
                return ResourceManager.GetString("FechaDeSuspension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificado Por.
        /// </summary>
        public static string ModificadoPor {
            get {
                return ResourceManager.GetString("ModificadoPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suspendido Por.
        /// </summary>
        public static string SuspendidoPor {
            get {
                return ResourceManager.GetString("SuspendidoPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Empleado.
        /// </summary>
        public static string TipoDeEmpleado {
            get {
                return ResourceManager.GetString("TipoDeEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Empleado Desc..
        /// </summary>
        public static string TipoDeEmpleadoDesc {
            get {
                return ResourceManager.GetString("TipoDeEmpleadoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Versión en Db.
        /// </summary>
        public static string VersionEnDb {
            get {
                return ResourceManager.GetString("VersionEnDb", resourceCulture);
            }
        }
    }
}
